// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ChessChallengeToolkit
{
    internal sealed partial class Vsix
    {
        public const string Id = "ChessChallengeToolkit.41c530d6-ee86-48cf-95f0-686aecefdda5";
        public const string Name = "ChessChallengeToolkit";
        public const string Description = @"An extension to show Bot Brain Capacity for Sebastian Lague's Tiny Chess Bots
https://github.com/SebLague/Chess-Challenge";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Bdavies329";
        public const string Tags = "";
    }
}
